Login feito
estartandodevs-course/Minha-Despensa-Frontend-TCC-2020 pull request #40
Opened 2020-12-09 01:40 UTC by Abraones

Necessário mudar o style

2020-12-09 13:11 UTC, Brenont requested changes
Tudo perfeito, só precisa mesmo remover a importação não utilizada pois está comprometendo o deploy

2020-12-09 13:11 UTC, Brenont commented on src/components/inputs-form/product-name/product-name.jsx
> +import React, { useState } from "react";
Remover a importação do useState já que ele não está sendo usado

2020-12-09 23:41 UTC, danilo7433 approved these changes

2020-12-09 23:43 UTC, danilo7433 approved these changes

2020-12-09 23:43 UTC, danilo7433 commented on src/components/inputs-form/product-name/product-name.jsx
> +import React, { useState } from "react";
opa, mudança feita

2020-12-10 17:38 UTC, LuizEduardoBP approved these changes

2020-12-10 17:39 UTC, LuizEduardoBP approved these changes

2020-12-10 17:46 UTC, Brenont approved these changes

2020-12-10 17:46 UTC, merged